version: '3.8'

services:
  mock-sftp-server:
    build: .
    container_name: mock-sftp-server
    ports:
      - "2222:22"
    environment:
      - SFTP_USERNAME=sftpuser
      - SFTP_PASSWORD=password
    volumes:
      - ./reports:/home/sftpuser/reports
    networks:
      - cmips-shared-network

networks:
  cmips-shared-network:
    external: true
    name: cmips-shared-network
